"""empty message

Revision ID: 483118456160
Revises: 642d3190e41b
Create Date: 2020-09-07 11:45:51.336149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483118456160'
down_revision = '642d3190e41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('shows', sa.Column('artist_image_link', sa.String(length=500), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('shows', 'artist_image_link')
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'address')
    # ### end Alembic commands ###
